services:
  stats-node:
    build: ./calculador-estadistica-node-api
    container_name: stats-node-container
    ports:
      - "7787:7787"
    environment:
      - PORT=7787
    networks:
      - matrix-net

  go-api:
    build: ./matriz-procesador-go-api
    container_name: go-api-container
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_API_URL=http://stats-node:7787/stats/calculate
    depends_on:
      - stats-node
    networks:
      - matrix-net

  frontend:
    build: ./matrix-frontend
    container_name: matrix-frontend-container
    ports:
      - "80:80"
    depends_on:
      - go-api
    networks:
      - matrix-net

networks:
  matrix-net:
    driver: bridge
